from random import randint

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

FP_TITLE = 'Flappy Python'

FP_PLAYER_IMG_SRC = 'assets/flappy_python_player.png'
FP_PLAYER_IMG_WIDTH = 100
FP_PLAYER_IMG_HEIGHT = 100

INIT_FP_PLAYER_POS_X = 100
INIT_FP_PLAYER_POS_Y = 100
INIT_FP_PLAYER_SPEED = 0  # initial speed 0 => no move

FP_PLAYER_SPEED_UP = -5
FP_PLAYER_SPEED_DOWN = 5

FP_BLOCKS_POS_X = SCREEN_WIDTH
FP_BLOCKS_POS_Y = 0
FP_BLOCKS_WIDTH = 75
FP_BLOCKS_GAP = FP_PLAYER_IMG_HEIGHT * 2
FP_BLOCKS_HEIGHT = randint(0, SCREEN_HEIGHT - FP_BLOCKS_GAP)
FP_BLOCKS_SPEED = 3
FP_BLOCKS_BG_COLOR = WHITE

FRAMES_PER_SECOND = 60
